plugins { id 'com.android.application' }
android {
    namespace 'com.dark.injector'
    compileSdk 34
    defaultConfig {
        applicationId "com.dark.injector"
        minSdk 24
        targetSdk 34
        externalNativeBuild { cmake { abiFilters 'arm64-v8a' } }
    }
    externalNativeBuild { cmake { path "src/main/cpp/CMakeLists.txt"; version "3.22.1" } }
    ndkVersion "25.2.9519653"
}
