name: Build Obsidian-Core
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # gradlew жоқ болса да, бұл action бәрін өзі реттейді
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug
